name: NPM Publish

on:
  push:
    branches:
      - npm

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Copy Schema
        run: cp playbook.schema.json typescript-sdk/

      - name: Publish to NPM
        run: npm publish --access public --provenance
        working-directory: typescript-sdk
